services:
  maniskill:
    container_name: maniskill_container
    image: ${IMAGE:-maniskill:latest}
    build:
      context: ..
      dockerfile: docker/Dockerfile
    network_mode: host
    pid: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - GPU=${GPU:-all}
      - MS_ASSET_DIR=/workspace/.maniskill
      - MS_SKIP_ASSET_DOWNLOAD_PROMPT=1
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
